# Seed data for products
products_data = [
    {
        "_id": "1",
        "name": "Emp. Jean Jacques Dessalines",
        "description": "Challenge coin honoring Jean-Jacques Dessalines, a leader of the Haitian Revolution and the first ruler of an independent Haiti under the 1805 constitution. He proclaimed himself Emperor Jacques I in 1804. This commemorative challenge coin celebrates his pivotal role in Haiti's independence.",
        "price": 25.00,
        "image": "https://images.squarespace-cdn.com/content/v1/67d6ef5142cdf803b50d47be/e08c4e83-f75c-4fff-b87e-d7bb73ae04ac/JJ+Dessalines+May+13%2C+2025%2C+07_44_25+PM.png",
        "status": "limited_stock",
        "category": "historical",
        "featured": True,
        "year": "1804",
        "material": "Zinc alloy with colorized enamel",
        "weight": "28g",
        "diameter": "39mm",
        "mintage": "Limited Edition"
    },
    {
        "_id": "2",
        "name": "Catherine Flon",
        "description": "Challenge coin celebrating Catherine Flon, the Haitian seamstress who sewed the first Haitian flag in 1803. This commemorative coin honors her crucial contribution to Haitian independence and national identity.",
        "price": 25.00,
        "image": "https://images.squarespace-cdn.com/content/v1/67d6ef5142cdf803b50d47be/5d3d4d20-30c3-4e65-8dad-aef98816c295/Catherine+Flon+Sewing+Haiti%27s+Flag+%281%29.png",
        "status": "coming_soon",
        "category": "historical",
        "featured": True,
        "year": "1803",
        "material": "Zinc alloy with colorized enamel",
        "weight": "28g",
        "diameter": "39mm",
        "mintage": "Limited Edition"
    },
    {
        "_id": "3",
        "name": "Sanite Belair",
        "description": "Challenge coin honoring Suzanne Bélair (Sanite Belair), a fearless Haitian freedom fighter and revolutionary who fought courageously alongside her husband in the Haitian Revolution. Freedom fighter. Revolutionary. Martyr. She refused a blindfold and faced execution with dignity and defiance — becoming an enduring symbol of Haitian resistance and womanhood.",
        "price": 25.00,
        "image": "https://images.squarespace-cdn.com/content/v1/67d6ef5142cdf803b50d47be/1a19b65d-3391-49ee-aaa0-0e9a9097b825/Lieutenant+Sanit%C3%A9+B%C3%A9lair+Commemorative+Coin.png",
        "status": "in_stock",
        "category": "historical",
        "featured": True,
        "year": "1802",
        "material": "Zinc alloy with colorized enamel",
        "weight": "28g",
        "diameter": "39mm",
        "mintage": "Limited Edition"
    },
    {
        "_id": "4",
        "name": "Marie-Jeanne Lamartinière",
        "description": "Challenge coin celebrating Marie-Jeanne Lamartinière, a Haitian revolutionary hero who fought valiantly in the Battle of Crête-à-Pierrot in 1802, one of the most important battles of the Haitian Revolution. This commemorative coin honors her extraordinary courage.",
        "price": 25.00,
        "image": "https://images.squarespace-cdn.com/content/v1/67d6ef5142cdf803b50d47be/ba62b6c3-d246-49ab-87bf-51346a134dac/Lamartiniere+Front.png",
        "status": "in_stock",
        "category": "historical",
        "featured": False,
        "year": "1802",
        "material": "Zinc alloy with colorized enamel",
        "weight": "28g",
        "diameter": "39mm",
        "mintage": "Limited Edition"
    },
    {
        "_id": "5",
        "name": "Alexandre Pétion",
        "description": "Challenge coin honoring Alexandre Pétion, the first President of the Republic of Haiti from 1807 until his death in 1818. He is considered one of the founding fathers of Haiti. This commemorative coin celebrates his leadership and vision for an independent Haiti.",
        "price": 25.00,
        "image": "https://images.squarespace-cdn.com/content/v1/67d6ef5142cdf803b50d47be/633d9a69-71a4-406a-b7e9-6371e54ac34f/ChatGPT+Image+May+14%2C+2025%2C+11_00_34+AM.png",
        "status": "coming_soon",
        "category": "presidential",
        "featured": False,
        "year": "1818",
        "material": "Zinc alloy with colorized enamel",
        "weight": "28g",
        "diameter": "39mm",
        "mintage": "Limited Edition"
    },
    {
        "_id": "6",
        "name": "Henri Christophe",
        "description": "Challenge coin celebrating Henri Christophe, a key leader in the Haitian Revolution who became King of Haiti in the northern part of the country from 1811 to 1820. Born in 1767, he rose through the ranks during Haiti's fight for independence. He is known for constructing the famous Citadelle Laferrière and Sans-Souci Palace.",
        "price": 25.00,
        "image": "https://images.squarespace-cdn.com/content/v1/67d6ef5142cdf803b50d47be/ddd0dd58-e259-44d3-82e0-01ffb435606d/King+Henri+Christophe+Bronze+Medallion.png",
        "status": "in_stock",
        "category": "royal",
        "featured": False,
        "year": "1811",
        "material": "Zinc alloy with colorized enamel",
        "weight": "28g",
        "diameter": "39mm",
        "mintage": "Limited Edition"
    },
    {
        "_id": "7",
        "name": "Heroines of Haiti Gift Set",
        "description": "Exclusive gift set featuring three heroines of the Haitian Revolution: Catherine Flon (the seamstress who sewed the first Haitian flag), Sanite Belair (fearless freedom fighter), and Marie-Jeanne Lamartinière (warrior of Crête-à-Pierrot). This commemorative collection celebrates the courage and sacrifice of Haiti's revolutionary women. Each coin is individually packaged in a premium display case with certificates of authenticity.",
        "price": 65.00,
        "image": "https://images.squarespace-cdn.com/content/v1/67d6ef5142cdf803b50d47be/5d3d4d20-30c3-4e65-8dad-aef98816c295/Catherine+Flon+Sewing+Haiti%27s+Flag+%281%29.png",
        "status": "in_stock",
        "category": "gift_set",
        "featured": True,
        "year": "1803-1804",
        "material": "Zinc alloy with colorized enamel",
        "weight": "84g (3 coins)",
        "diameter": "39mm each",
        "mintage": "Limited Edition"
    },
    {
        "_id": "8",
        "name": "Founders Collection Gift Set",
        "description": "Complete commemorative set honoring the founding fathers of Haiti's independence. Includes Emperor Jean-Jacques Dessalines, King Henri Christophe, and President Alexandre Pétion. This premium gift set celebrates the leaders who shaped Haiti into the first Black-led republic. Perfect for collectors and history enthusiasts. Comes in an elegant presentation box with historical documentation.",
        "price": 70.00,
        "image": "https://images.squarespace-cdn.com/content/v1/67d6ef5142cdf803b50d47be/e08c4e83-f75c-4fff-b87e-d7bb73ae04ac/JJ+Dessalines+May+13%2C+2025%2C+07_44_25+PM.png",
        "status": "in_stock",
        "category": "gift_set",
        "featured": True,
        "year": "1804-1820",
        "material": "Zinc alloy with colorized enamel",
        "weight": "84g (3 coins)",
        "diameter": "39mm each",
        "mintage": "Limited Edition"
    },
    {
        "_id": "9",
        "name": "Complete Revolutionary Heroes Collection",
        "description": "The ultimate collection featuring all six revolutionary heroes of Haiti. This comprehensive gift set includes Dessalines, Catherine Flon, Sanite Belair, Marie-Jeanne Lamartinière, Alexandre Pétion, and Henri Christophe. Each coin tells the story of Haiti's remarkable journey to independence. Presented in a luxurious wooden display case with individual compartments and a commemorative booklet detailing each hero's contributions.",
        "price": 140.00,
        "image": "https://images.squarespace-cdn.com/content/v1/67d6ef5142cdf803b50d47be/5b2777b5-67d8-4e5b-b2ad-73d8011ad3fb/Galer%C3%ADa+de+Monedas+Hist%C3%B3ricas.png",
        "status": "in_stock",
        "category": "gift_set",
        "featured": False,
        "year": "1802-1820",
        "material": "Zinc alloy with colorized enamel",
        "weight": "168g (6 coins)",
        "diameter": "39mm each",
        "mintage": "Limited Edition",
        "sale_price": 120.00,
        "sale_label": "Independence Day Sale"
    },
    {
        "_id": "10",
        "name": "Premium Challenge Coin Display Holder",
        "description": "Elegant wooden display holder designed specifically for 39mm challenge coins. Features velvet-lined compartments to protect and showcase your commemorative coins. Holds up to 6 coins with individual slots. Perfect for displaying your collection of Haitian revolutionary heroes. Made from solid mahogany with a glass front panel and easel back for tabletop display.",
        "price": 35.00,
        "image": "https://images.unsplash.com/photo-1565374838638-8c0e9f79c97a?w=500&h=500&fit=crop",
        "status": "in_stock",
        "category": "accessories",
        "featured": False,
        "year": "2025",
        "material": "Mahogany wood with glass panel",
        "weight": "450g",
        "diameter": "8x10 inches",
        "mintage": "Always Available"
    },
    {
        "_id": "11",
        "name": "Haitian Heroes Trophy - Courage Award",
        "description": "Stunning recognition trophy featuring a bronze-finished challenge coin mount. Perfect for honoring individuals who embody the courage and leadership of Haiti's revolutionary heroes. Includes customizable engraving plate. Ideal for schools, community organizations, and special recognition ceremonies. The trophy stands 10 inches tall on a weighted black marble base.",
        "price": 45.00,
        "image": "https://images.unsplash.com/photo-1624526267942-ab0ff8a3e972?w=500&h=500&fit=crop",
        "status": "in_stock",
        "category": "accessories",
        "featured": False,
        "year": "2025",
        "material": "Bronze finish with marble base",
        "weight": "800g",
        "diameter": "10 inches height",
        "mintage": "Always Available"
    },
    {
        "_id": "12",
        "name": "Revolutionary Hero Medallion Bottle Opener",
        "description": "Functional art meets history! This premium bottle opener features a commemorative medallion design inspired by Haiti's revolutionary heroes. Crafted from solid brass with an antique finish. Makes a perfect gift for collectors and history enthusiasts. Each opener is individually numbered and comes in a gift box. Opens bottles while honoring the heroes who opened the door to freedom.",
        "price": 18.00,
        "image": "https://images.unsplash.com/photo-1608686207856-001b95cf60ca?w=500&h=500&fit=crop",
        "status": "in_stock",
        "category": "accessories",
        "featured": False,
        "year": "2025",
        "material": "Solid brass with antique finish",
        "weight": "120g",
        "diameter": "4 inches",
        "mintage": "Always Available"
    },
    {
        "_id": "13",
        "name": "Heroes of Haiti Coloring Book for Children",
        "description": "Educational coloring book introducing children to Haiti's revolutionary heroes. Features 32 pages of beautifully illustrated scenes from Haiti's history including Catherine Flon sewing the flag, Jean-Jacques Dessalines leading troops, and other inspiring moments. Each page includes fun facts and simple explanations suitable for ages 5-12. Printed on high-quality paper perfect for crayons, colored pencils, and markers. A wonderful way to teach children about courage, freedom, and Haitian heritage.",
        "price": 12.00,
        "image": "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=500&h=500&fit=crop",
        "status": "in_stock",
        "category": "children",
        "featured": True,
        "year": "2025",
        "material": "32-page coloring book",
        "weight": "150g",
        "diameter": "8.5x11 inches",
        "mintage": "Always Available",
        "sale_price": 10.00,
        "sale_label": "Back to School Sale"
    },
    {
        "_id": "14",
        "name": "Build Your Own Heroes Gift Set",
        "description": "Create a personalized gift set by choosing any 3 challenge coins from our collection! Perfect for gifting or creating your own curated collection. Your selection will be beautifully packaged in our premium gift box with individual protective sleeves and certificates of authenticity. Select your heroes during checkout. Price includes premium packaging and display case.",
        "price": 68.00,
        "image": "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=500&h=500&fit=crop",
        "status": "in_stock",
        "category": "custom",
        "featured": True,
        "year": "2025",
        "material": "Your choice of 3 coins",
        "weight": "84g (3 coins)",
        "diameter": "39mm each",
        "mintage": "Made to Order"
    }
]
