# Seed data for products
products_data = [
    {
        "_id": "1",
        "name": "Emp. Jean Jacques Dessalines",
        "description": "Challenge coin honoring Jean-Jacques Dessalines, a leader of the Haitian Revolution and the first ruler of an independent Haiti under the 1805 constitution. He proclaimed himself Emperor Jacques I in 1804. This commemorative challenge coin celebrates his pivotal role in Haiti's independence.",
        "price": 25.00,
        "image": "https://images.squarespace-cdn.com/content/v1/67d6ef5142cdf803b50d47be/e08c4e83-f75c-4fff-b87e-d7bb73ae04ac/JJ+Dessalines+May+13%2C+2025%2C+07_44_25+PM.png",
        "status": "limited_stock",
        "category": "historical",
        "featured": True,
        "year": "1804",
        "material": "Zinc alloy with colorized enamel",
        "weight": "28g",
        "diameter": "39mm",
        "mintage": "Limited Edition"
    },
    {
        "_id": "2",
        "name": "Catherine Flon",
        "description": "Challenge coin celebrating Catherine Flon, the Haitian seamstress who sewed the first Haitian flag in 1803. This commemorative coin honors her crucial contribution to Haitian independence and national identity.",
        "price": 25.00,
        "image": "https://images.squarespace-cdn.com/content/v1/67d6ef5142cdf803b50d47be/5d3d4d20-30c3-4e65-8dad-aef98816c295/Catherine+Flon+Sewing+Haiti%27s+Flag+%281%29.png",
        "status": "coming_soon",
        "category": "historical",
        "featured": True,
        "year": "1803",
        "material": "Zinc alloy with colorized enamel",
        "weight": "28g",
        "diameter": "39mm",
        "mintage": "Limited Edition"
    },
    {
        "_id": "3",
        "name": "Sanite Belair",
        "description": "Challenge coin honoring Suzanne Bélair (Sanite Belair), a fearless Haitian freedom fighter and revolutionary who fought courageously alongside her husband in the Haitian Revolution. Freedom fighter. Revolutionary. Martyr. She refused a blindfold and faced execution with dignity and defiance — becoming an enduring symbol of Haitian resistance and womanhood.",
        "price": 25.00,
        "image": "https://images.squarespace-cdn.com/content/v1/67d6ef5142cdf803b50d47be/1a19b65d-3391-49ee-aaa0-0e9a9097b825/Lieutenant+Sanit%C3%A9+B%C3%A9lair+Commemorative+Coin.png",
        "status": "in_stock",
        "category": "historical",
        "featured": True,
        "year": "1802",
        "material": "Zinc alloy with colorized enamel",
        "weight": "28g",
        "diameter": "39mm",
        "mintage": "Limited Edition"
    },
    {
        "_id": "4",
        "name": "Marie-Jeanne Lamartinière",
        "description": "Challenge coin celebrating Marie-Jeanne Lamartinière, a Haitian revolutionary hero who fought valiantly in the Battle of Crête-à-Pierrot in 1802, one of the most important battles of the Haitian Revolution. This commemorative coin honors her extraordinary courage.",
        "price": 25.00,
        "image": "https://images.squarespace-cdn.com/content/v1/67d6ef5142cdf803b50d47be/ba62b6c3-d246-49ab-87bf-51346a134dac/Lamartiniere+Front.png",
        "status": "in_stock",
        "category": "historical",
        "featured": False,
        "year": "1802",
        "material": "Zinc alloy with colorized enamel",
        "weight": "28g",
        "diameter": "39mm",
        "mintage": "Limited Edition"
    },
    {
        "_id": "5",
        "name": "Alexandre Pétion",
        "description": "Challenge coin honoring Alexandre Pétion, the first President of the Republic of Haiti from 1807 until his death in 1818. He is considered one of the founding fathers of Haiti. This commemorative coin celebrates his leadership and vision for an independent Haiti.",
        "price": 25.00,
        "image": "https://images.squarespace-cdn.com/content/v1/67d6ef5142cdf803b50d47be/633d9a69-71a4-406a-b7e9-6371e54ac34f/ChatGPT+Image+May+14%2C+2025%2C+11_00_34+AM.png",
        "status": "coming_soon",
        "category": "presidential",
        "featured": False,
        "year": "1818",
        "material": "Zinc alloy with colorized enamel",
        "weight": "28g",
        "diameter": "39mm",
        "mintage": "Limited Edition"
    },
    {
        "_id": "6",
        "name": "Henri Christophe",
        "description": "Challenge coin celebrating Henri Christophe, a key leader in the Haitian Revolution who became King of Haiti in the northern part of the country from 1811 to 1820. Born in 1767, he rose through the ranks during Haiti's fight for independence. He is known for constructing the famous Citadelle Laferrière and Sans-Souci Palace.",
        "price": 25.00,
        "image": "https://images.squarespace-cdn.com/content/v1/67d6ef5142cdf803b50d47be/ddd0dd58-e259-44d3-82e0-01ffb435606d/King+Henri+Christophe+Bronze+Medallion.png",
        "status": "in_stock",
        "category": "royal",
        "featured": False,
        "year": "1811",
        "material": "Zinc alloy with colorized enamel",
        "weight": "28g",
        "diameter": "39mm",
        "mintage": "Limited Edition"
    },
    {
        "_id": "7",
        "name": "Heroines of Haiti Gift Set",
        "description": "Exclusive gift set featuring three heroines of the Haitian Revolution: Catherine Flon (the seamstress who sewed the first Haitian flag), Sanite Belair (fearless freedom fighter), and Marie-Jeanne Lamartinière (warrior of Crête-à-Pierrot). This commemorative collection celebrates the courage and sacrifice of Haiti's revolutionary women. Each coin is individually packaged in a premium display case with certificates of authenticity.",
        "price": 65.00,
        "image": "https://images.squarespace-cdn.com/content/v1/67d6ef5142cdf803b50d47be/5d3d4d20-30c3-4e65-8dad-aef98816c295/Catherine+Flon+Sewing+Haiti%27s+Flag+%281%29.png",
        "status": "in_stock",
        "category": "gift_set",
        "featured": True,
        "year": "1803-1804",
        "material": "Zinc alloy with colorized enamel",
        "weight": "84g (3 coins)",
        "diameter": "39mm each",
        "mintage": "Limited Edition"
    },
    {
        "_id": "8",
        "name": "Founders Collection Gift Set",
        "description": "Complete commemorative set honoring the founding fathers of Haiti's independence. Includes Emperor Jean-Jacques Dessalines, King Henri Christophe, and President Alexandre Pétion. This premium gift set celebrates the leaders who shaped Haiti into the first Black-led republic. Perfect for collectors and history enthusiasts. Comes in an elegant presentation box with historical documentation.",
        "price": 70.00,
        "image": "https://images.squarespace-cdn.com/content/v1/67d6ef5142cdf803b50d47be/e08c4e83-f75c-4fff-b87e-d7bb73ae04ac/JJ+Dessalines+May+13%2C+2025%2C+07_44_25+PM.png",
        "status": "in_stock",
        "category": "gift_set",
        "featured": True,
        "year": "1804-1820",
        "material": "Zinc alloy with colorized enamel",
        "weight": "84g (3 coins)",
        "diameter": "39mm each",
        "mintage": "Limited Edition"
    },
    {
        "_id": "9",
        "name": "Complete Revolutionary Heroes Collection",
        "description": "The ultimate collection featuring all six revolutionary heroes of Haiti. This comprehensive gift set includes Dessalines, Catherine Flon, Sanite Belair, Marie-Jeanne Lamartinière, Alexandre Pétion, and Henri Christophe. Each coin tells the story of Haiti's remarkable journey to independence. Presented in a luxurious wooden display case with individual compartments and a commemorative booklet detailing each hero's contributions.",
        "price": 140.00,
        "image": "https://images.squarespace-cdn.com/content/v1/67d6ef5142cdf803b50d47be/5b2777b5-67d8-4e5b-b2ad-73d8011ad3fb/Galer%C3%ADa+de+Monedas+Hist%C3%B3ricas.png",
        "status": "in_stock",
        "category": "gift_set",
        "featured": False,
        "year": "1802-1820",
        "material": "Zinc alloy with colorized enamel",
        "weight": "168g (6 coins)",
        "diameter": "39mm each",
        "mintage": "Limited Edition"
    }
]
